### ISSUE TITLE
On_action long term fix.

### ISSUE THREAD

**Issue by mellester** [TheDivexz/excelmakesbelhappypack#10]
My suggestion is to move every line in the_onaction to a event per mod pack.
So in the future when those get updated we can just copy paste.

**Comment by stackpoint** [comment]
There are currently duplicate on_actions which cause them to overwrite each other. They also just need to be merged in the first place.

**Comment by stackpoint** [comment]
Merged the final on_actions here: https://github.com/TheDivexz/excelmakesbelhappypack/commit/4a1e56d9157b00d8b9f04795948a862fcf99e51c
