### ISSUE TITLE
Having Interface Elements Overlapping (1.30 Austria Version) 

### ISSUE THREAD

**Issue by plak20** [TheDivexz/excelmakesbelhappypack#121]
As the title says, I have recently updated the mod and have since tried to start a new campaing but it was quickly stopped due to this problem:

![20201202135122_1](https://user-images.githubusercontent.com/22401618/100906635-2384fc00-34a8-11eb-9273-160cc75b6367.jpg)

  I have had problems in the past with the interface but I cant find a way to work around this one since, when right clicking any country, the top left thingy (where your flag, name and monarch points is displayed) seems to get priority over any other interface element until the game is restarted and when clicking the warning for possible provinces to state, it will automaticly take me to the "edicts window" (where you can state and unstate provinces) and I'm unable to go back.

  I have said problem most likely because of my 1366x768 monitor, but is there any way I can fix this, I have already tried the 0.9 GUI size with no result and have been looking around the interface folder to try and find a way to reduce the province view window somehow or give it priority over the top left "flag and name" tab 
  Any help would be welcomed

(I still dont know how to lable a github post, sorry)

**Comment by Stiopa866** [comment]
@afowl

**Comment by FelipeFelps** [comment]
I had trouble with It as well, and the only way around It is using hotkeys and the macro builder, instead of clicking on x on the interface Just use esc, on the province interface you can use f or s, one of those, to change between the province overview and the state one, for deving and making states go to the macro builder. Only thing that looks unusable is the parliament seat thing.

**Comment by FelipeFelps** [comment]
I tried deleting interface folder, it breaks buildings :/

**Comment by plak20** [comment]
Update: Hey! pressing S actualy works, I never had to used those hotkeys before so I had no idea they even existed, thanks alot

Btw, should I close the issue now?

**Comment by stackpoint** [comment]
For future reference: 

![image](https://user-images.githubusercontent.com/5704491/111043502-05079880-83e7-11eb-9e34-237616063600.png)
