### ISSUE TITLE
Chugsworth Nov 30 @ 12:09am 

### ISSUE THREAD

**Issue by Belusterk** [TheDivexz/excelmakesbelhappypack#122]
Trying to complete the Persian "Spread the Imamiyyah" mission causes the game to crash.

**Comment by stackpoint** [comment]
Is this with steam or github?

**Comment by Belusterk** [comment]
Steam

**Comment by Belusterk** [comment]
I Updated Steam on Nov 27 @ 7:17am

**Comment by stackpoint** [comment]
Could not replicate the bug. You can ask them to upload a save and modlist.
