### ISSUE TITLE
Wrong modifier added?

### ISSUE THREAD

**Issue by Aleksejus1** [TheDivexz/excelmakesbelhappypack#125]
I was playing with this mod and took the enhanced reform called "Empowered Church Councils" but noticed that my provinces with tax building were not getting the production benefit, then i looked into the files of the mod and noticed that for some reason it's giving the Town_Rights modifier instead of Church_Poorhouses, i've linked that part of code here.
https://github.com/TheDivexz/excelmakesbelhappypack/blob/614117fde1bca25b9a630227a0668a1c9f98486c/events/ReformEvents.txt#L5101
I fixed it manually for myself, but just letting y'all know so that you could fix it for others as well :)

**Comment by stackpoint** [comment]
Fixed here: https://github.com/TheDivexz/excelmakesbelhappypack/commit/9ed3f518edcb7c9fcfefd576086f386f4548db97
