### ISSUE TITLE
Infinite WHILE - flavorKOR.txt

### ISSUE THREAD

**Issue by stackpoint** [TheDivexz/excelmakesbelhappypack#14]
Vanilla events file flavorKOR.txt causing infinite WHILE loop with event flavor_kor.10

Most likely to do with the estate modification but its probably safer to disable the event chain since it can cause crashes.

`[basiceffects.cpp:386]: Warning: while-loop aborted after executing 100000 times`

**Comment by mellester** [comment]
This seems to be becuase korea doesnt have 3 provinces to assgin the burghers too.
As in this event assumes there are 3 provinces to assgin the burgers too and whiles until it does

**Comment by stackpoint** [comment]
It checks the remaining provinces within the while loop so you shouldn't need to check it at the start of the event.

**Comment by stackpoint** [comment]
```
while = {
	limit = {
		NOT = {
			num_of_owned_provinces_with = { #<3
				value = 3
				has_estate = estate_burghers
			}
		}
		any_owned_province = { #qualified nonburgher provinces
			is_state_core = root
			is_capital = no
			culture = korean
			NOT = { has_estate = estate_burghers }
		}
	}
```

The while loop checks if there are <3 burghers AND if there are any provinces left to assign to them.

**Comment by mellester** [comment]
Your right I seems to not understand why it breaks. becuase it should indeed  give 3 estates to the burgers unless there are less than 3 korean culture stated non capital cores. which might be the case

**Comment by stackpoint** [comment]
It could be an estate problem since the modpack did extensive work to the estates files.

**Comment by stackpoint** [comment]
@mellester did this: https://github.com/mellester/excelmakesbelhappypack/commit/2f54b61ce55601ffe26aa383b7a5387529746a07 actually fix the issue? I thought the vanilla loop logic was okay? I don't think it made the master branch either.

**Comment by stackpoint** [comment]
Fixed. See: https://github.com/TheDivexz/excelmakesbelhappypack/commit/1f57918a8696ce29fc26db4a71d4298964595b63
