### ISSUE TITLE
Experimental Building Order for AI

### ISSUE THREAD

**Issue by stackpoint** [TheDivexz/excelmakesbelhappypack#20]
By Spirit Baker on Discord:

https://www.dropbox.com/sh/bspowrminl84vle/AADx8P_5LyL7NVRNsCb0GVDIa?dl=0

- experimental building order for AI, should generally work, needs further testing tho
- AI only decision for building fort in a capital, cripples small AI's that just have 5 monthly income to press it, I've seen AI building forts without it
- I think 0 weight modifier next  to has_construction = building,  blocks big AI's from building it right away
- Coz every time something is building around capital weight drops to 0, means the AI stops saving for fort
- I've seen france building it without the decision, early on

**Comment by SpiritBaker** [comment]
Issues with Courthouse and Town Halls, AI doesn't see free building slot and hardcoded to replace them if he needs an extra slot. Stops AI from functioning properly. Only permanent solution that comes to my mind, is to disable 2 first tiers for AI 

Issues with ME building, AI builds them even with ai_will_do = 0. Possibly also freezes the AI as result.

Makes plzbuildfortdummy.txt decision redundant

**Comment by stackpoint** [comment]
Will make sure to disable the decision if it works as intended.

**Comment by SpiritBaker** [comment]
Updated the dropbox, disabling ME buildings. AI should avoid building Courthouse and Town Halls. 

If u have nothing to do, keep the game running in background with this.

**Comment by SpiritBaker** [comment]
Updated the dropbox again. Fixed most of the stuff.  
Blocked AI from replacing buildings with free building slot. That was the cause for most of the issues.

**Comment by stackpoint** [comment]
Then do we still have to remove the shipyard from Venice? Or the ME buildings?

**Comment by SpiritBaker** [comment]
I've simplified the trigger for Shipyard and Docks, they only require ideas now. They both can be build in province now, and that was the main problem.  So even ideas requirement can be potentially dropped. 

AI is still able to build ME buildings somehow, but it does not causes any problems anymore.  

Court House, Town Hall line up can potentially cause issues for opm's and Small AI's. The value set to 0.1 except for the last tier.  For some reason they have relatively high hardcoded wight, and AI likes to replace them. When they have free building slot, this means AI will stop functioning. 
My suggestion is to move this free building slot to Forts, AI almost never replaces Forts.

**Comment by SpiritBaker** [comment]
Updated dropbox again. I've checked most of the buildings, AI builds and upgrades them. 
Simplified triggers, tweaked AI values. 
Added Freebuilding slot to a Fort.
Removed Fort level and zone of control from Naval base.

**Comment by stackpoint** [comment]
Since you've tested it so much I wouldn't mind placing it into the master branch for testing but decisions about balancing would need to go through someone like @Belusterk or Arumba.

**Comment by SpiritBaker** [comment]
Well I'm just suggesting this changes, the only crutuail one is zone of control on Naval base. I think it adds maintenance modifier to Naval Base. I've tried different values went to 1000+ range and it was not enough.  Without it AI builds Naval Bases at value 0.5, force limit modifiers have very high hardcoded value.

**Comment by stackpoint** [comment]
The build order AI is bugging out when given buildings. Not sure if it's the ME specific buildings or when the AI doesn't have the tech to build the buildings themselves. All I am sure for certain is that the AI won't hold on to their gold when all the add_building code gets commented out.

**Comment by stackpoint** [comment]
Thanks for your contribution @Ivanjpeg I made a new branch with your changes and once I finish the ME add_building fixes I will push it to master. Was there any other changes you've made?

**Comment by SpiritBaker** [comment]
Everything on the future branch. Only balance issues remain and the fact that AI is not upgrading trade centers.

**Comment by stackpoint** [comment]
Thanks for you patience. I have your tweaks and the event/mission building fixes so the AI will not be getting future buildings/over building limit, in this branch here: https://github.com/TheDivexz/excelmakesbelhappypack/tree/build-order-2

If you could help me test this, I will push it to master with your green light.

**Comment by stackpoint** [comment]
@Ivanjpeg  Thanks for you patience. I have your tweaks and the event/mission building fixes so the AI will not be getting future buildings/over building limit, in this branch here: https://github.com/TheDivexz/excelmakesbelhappypack/tree/build-order-2

If you could help me test this, I will push it to master with your green light and a final pass through.
