### ISSUE TITLE
Increase Development Button cant be clicked

### ISSUE THREAD

**Issue by Belusterk** [TheDivexz/excelmakesbelhappypack#23]
![image](https://user-images.githubusercontent.com/51682017/79629343-09fc9300-8117-11ea-8ae7-89d7d63b50ae.png)

Idk if this cant be done by the player, i looked at the code but i see only ai can use this

**Comment by stackpoint** [comment]
Looking at the code right now, players should be able to click the button at least. Give yourself max mil power and see if you can click on it.

**Comment by Belusterk** [comment]
![image](https://user-images.githubusercontent.com/51682017/79629472-19301080-8118-11ea-9e51-e8df87d06c80.png)

**Comment by stackpoint** [comment]
Can you post your error.log file? I can't boot up the game at the moment so I can't test it in game at the moment.

**Comment by Belusterk** [comment]
[error.log](https://github.com/TheDivexz/excelmakesbelhappypack/files/4496143/error.log)

**Comment by stackpoint** [comment]
I'm not 100% familiar with paradox syntax but there is missing spaces between the '=' signs which could be causing errors.

**Comment by stackpoint** [comment]
Okay thanks for the file. Found possible errors. Will post again in a second.

**Comment by stackpoint** [comment]
Okay, found the missing brackets. I'm not sure if that will have fixed it though. Please let me know.

**Comment by mellester** [comment]
nice job

**Comment by stackpoint** [comment]
@mellester I have an update coming up in a second. If you can take a look.
