### ISSUE TITLE
Issues with mission buildings 

### ISSUE THREAD

**Issue by SpiritBaker** [TheDivexz/excelmakesbelhappypack#24]
![wrssz](https://user-images.githubusercontent.com/34450337/79630595-7d80bd80-8174-11ea-8141-b4bc4e0deb43.png)
Two Tax buildings of different tiers in the same province 

![missionsPOL](https://user-images.githubusercontent.com/34450337/79630627-c0db2c00-8174-11ea-9b23-8e8a59ca2951.png)

**Comment by stackpoint** [comment]
Fixed here: https://github.com/TheDivexz/excelmakesbelhappypack/tree/build-order-2
