### ISSUE TITLE
Clearing Error.log and the Validator

### ISSUE THREAD

**Issue by stackpoint** [TheDivexz/excelmakesbelhappypack#30]
Going to start going down the list and working on errors:
- [x] [[province.cpp:364]: _Discovered capacity should be at least 1216](https://github.com/TheDivexz/excelmakesbelhappypack/issues/30#issuecomment-620937144)
- [ ] [province.cpp:8438]: Invalid tag trying to discover province [X] - [Province]

**Comment by mellester** [comment]
[province.cpp:364]: _Discovered capacity should be at least 1216

Extensivly googled this error. Nobody knows how to fix it

**Comment by stackpoint** [comment]
[province.cpp:364]: _Discovered capacity should be at least 1216

I did some testing on this and it seems like you can only define 814 tags in the /common/country_tags/ folder before this error starts appearing. We could delete some vanilla tags to make room for the 16 tags ME is over but that seems a bit drastic.

**Comment by stackpoint** [comment]
I can't believe it, reducing the allotted slots for custom nations actually fixed it:
```
NDefines.NGame.MAX_CUSTOM_COUNTRIES = 50
```

**Comment by stackpoint** [comment]
Cleared all non-trivial errors out of the error.log file. See: https://github.com/TheDivexz/excelmakesbelhappypack/commit/8ec45e58495184becaba8c646fd7d7cde35d4296

**Comment by stackpoint** [comment]
Cleared all non-trivial errors out of the error.log file. See:

**Comment by stackpoint** [comment]
Some errors while the game was running:
```
[gamestate.cpp:7179]: Undefined event target tooltip: decentralize_cycle_GE_neg
[gamestate.cpp:7139]: Undefined event target: decentralize_cycle_GE_neg
[gamestate.cpp:7139]: Undefined event target: expel_heathens_cycle_GE_pos
[gamestate.cpp:7303]: Undefined monarch/heir: expel_heathens_cycle_GE_pos
[ck2text.cpp:267]: Unknown text property 'GetName] to be expelled from our nation. Let us resettle the place with proper members of the faith, but what incentive should we grant them?'
[gamestate.cpp:7139]: Undefined event target: refused_the_call_cycle_GE
[gamestate.cpp:7179]: Undefined event target tooltip: refused_the_call_cycle_GE
[eventtarget.cpp:341]: Undefined event target: refused_the_call_cycle_GE
[flags.cpp:173]: Trying to get undefined non-dynamic flag: 'lottery_candidate_a_@ROOT'
```
