### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by JamesMConroy** [TheDivexz/excelmakesbelhappypack#32]
Some things to clean up are:
- "also other improvemnts to ai and develment ideas"
  - develment should be development
- "Startup events know includes"
  - know should be now
- "plugged in Theatrum Orbis Terrarum graphich pack"
  - graphich should be graphics
- "fixed integrate Moneyloaners not working"
  - Moneyloaners should be Moneylenders

**Comment by JamesMConroy** [comment]
Created pull request #33 for this

**Comment by stackpoint** [comment]
Did you get everything in that pull?

**Comment by mellester** [comment]
looked good pull has been accepted
