### ISSUE TITLE
Rebels go from 10% to 100% within one month

### ISSUE THREAD

**Issue by Killuah2k** [TheDivexz/excelmakesbelhappypack#42]
Hi,

not sure if it's a bug (or a feature). Also not sure if it's caused by the modpack.

While beeing at war peasant rebels in West Java (all 5 provinces have 3.5 unrest -> 14.6% chance to increase) instantly move from 10% to 100% between 02/1490 and 03/1490.

![Rebels](https://user-images.githubusercontent.com/3479917/80532492-89eaee80-899c-11ea-9656-80a2fdcf89d7.PNG)

Savefile:
[Palembang1490_02_23.zip]https://github.com/TheDivexz/excelmakesbelhappypack/files/4548205/Palembang1490_02_23.zip)

**Comment by stackpoint** [comment]
This is really strange. I'm not entirely familiar with the rebel mechanics but I believe they're only supposed to increase 10% a month. Using harsh treatment causes them to increase at unusual percentages too. Please let us know if this happens again.
