### ISSUE TITLE
Wales Cannot Complete "Fate of Wales"

### ISSUE THREAD

**Issue by rieger07** [TheDivexz/excelmakesbelhappypack#43]
Loving the pack guys! Ran into an issue though...

I made it through 99% of the `missions expanded` mission tree of wales.
Completed "A burgeoning kingdom" (`WLS_parliment_1`) ... i'm pretty sure that the "Senned" is never actually built/started, or the event never fired or something is missing. 

References `WLS_parliment_1` and `WLS_parliment_2` in [ME_Wales_Braelyc_Cymru_Missions.txt](https://github.com/TheDivexz/excelmakesbelhappypack/blob/master/missions/ME_Wales_Braelyc_Cymru_Missions.txt)

I went and looked at the hidden event `ME_Wales_Events.2` which is triggered in 10y by `WLS_parliment_1`, and it doesn't mention anything obvious to me about building `production_lvl_4` or `counting_house`. And a quick search in [ME_Wales_Braelyc_Cymru_Events.txt](https://github.com/TheDivexz/excelmakesbelhappypack/blob/master/events/ME_Wales_Braelyc_Cymru_Events.txt) didn't yield anything when searching for either building.

I then tried to complete fate of wales, 
![image](https://user-images.githubusercontent.com/5598803/80758095-2b8c5000-8b03-11ea-9e32-939102bc4a6e.png) And it looks like i cannot meet the requirements because of an invalid building id.

I tracked it down to [Idea Variation Buildings.txt](https://github.com/TheDivexz/excelmakesbelhappypack/blob/master/common/buildings/Idea%20Variation%20Buildings.txt#L381)

Looks like at some point `production_lvl_4` became `counting_house` or something like that without updating what building to check for in `WLS_parliment_2`.
Not sure what the right fix is. I can make the changes and do a pull request if that's helpful. I just need to know how you think it should be handled.

Possible fix:
* when completing WLS_parliment_1 it has a hidden event that will fire in 10y. Add another result to both choices that builds counting_house
* change WLS_parliment_2 to reference counting_house? e.g.
```
	WLS_parliment_2 = { #Preserve our culture
		icon = me_mission_wales_flower
		required_missions = { 
			WLS_parliment
		}
		position = 6
		provinces_to_highlight = {
			owned_by = ROOT
			OR = {
				NOT = { culture = english }
				AND = {
					is_capital_of = ROOT
					NOT = { has_building = counting_house}
				}
			}
		}
		trigger = {
			num_of_owned_provinces_with = {
				value = 20
				culture = english
			}
			capital_scope = {
				has_building = counting_house
			}
			if = {
				limit = {
					has_dlc = "Common Sense"
				}
				has_parliament = yes
			}
			else = {
				OR = {
					plutocracy_ideas = 3
					has_reform = administrative_monarchy
					has_reform = administrative_republic
				}
			}
			total_development = 300
		}
		effect = {
			add_country_modifier = {
				name = wls_parliment_mod
				duration = -1
			}
			country_event = { id = ME_Wales_Events.3 }
		}
	}
```
* Does it make sense for this event to build a counting_house though?

**Comment by stackpoint** [comment]
Maybe the courthouse line. I'll take a look when I go through the missions tonight. Thanks for such a detailed report.

**Comment by Grociu** [comment]
Did some testing on this. Results:
1. In principle changing all instances of `production_lvl_4` to `counting_house` in `WLS_parliment` AND `WLS_parliment_2` works as a fix for this. The conditions are met, the building is being built, the building finishes and event fires in 10 years, If I decide I want parliament, I can complete the next mission.
2. `counting_house` is actually the Huge Workshop.
Active localizations on master seem to be:
`building_counting_house:0 "Huge Workshop"` in `zIdea_Variation_replace_l_english.yml`
`building_production_lvl_3:0 "Counting House"` in `Idea_Variation_buildings_l_english.yml`
3. I think maybe a production building for this particular event does not fit (building a seat of power) and the government tier 4 building might be better.

**Comment by stackpoint** [comment]
Around what year do we expect players to get to this mission?

**Comment by Grociu** [comment]
You need to not be a subject of England and have 15 non-Welsh culture cores. How many wars would that take for an average player?

**Comment by rieger07** [comment]
> You need to not be a subject of England and have 15 non-Welsh culture cores. How many wars would that take for an average player?

I can say I got to the final mission that was broken @1540ish, but I got lucky with an unholy alliance with castille/france to break free.

**Comment by stackpoint** [comment]
We could predicate it on the third government building then that spawns at adm tech 16, year 1609.

**Comment by stackpoint** [comment]
Okay, I've pushed a fix on the build-order-2 branch. It may require tweaks based on balance but that's a whole different discussion.

I moved the building requirement over to the courthouse line and required the level 3 building to complete the final mission.

**Comment by stackpoint** [comment]
What likely happened in the original files is that WLS_parliment was supposed to build a production_lvl_4 that would complete in 10(!!!) years. But it would also skip that construction if you were building something in your capital but not restrict you from pressing the button. So you could complete the mission but skip starting the construction....
```
					if = {
						limit = {
							NOT = { has_building = production_lvl_4 }
							NOT = { has_construction = core }
							NOT = { has_construction = building }
							NOT = { has_construction = culture }
							NOT = { has_construction = missionary }
						}
						add_building_construction = {
							building = production_lvl_4
							speed = 10.0
							cost = 0.0
						}
					}
```
