### ISSUE TITLE
Not existing Ideas groups.

### ISSUE THREAD

**Issue by mellester** [TheDivexz/excelmakesbelhappypack#45]
Some idea groups don't exist anymore so events and decision form vanilla break sometimes.
My suggestion is to use find and replace in all files to replace every mention with another set of ideas.
prevarbly more than 1.

**Comment by stackpoint** [comment]
I believe I've caught most of them. Just need to add AI personalities file in.

**Comment by mellester** [comment]
Alright :thumbs up:  reg ideas is a tricky one because it still exist.

**Comment by stackpoint** [comment]
Ah, I need to check the vanilla religious ideas, that's right. I've caught all the religious ideas in the modpack but not the vanilla references.

**Comment by stackpoint** [comment]
I believed fixed here: https://github.com/TheDivexz/excelmakesbelhappypack/commit/189831e951665168d81ceef080b4dec1d9d8f406
