### ISSUE TITLE
Hard mode scaling modifiers

### ISSUE THREAD

**Issue by stackpoint** [TheDivexz/excelmakesbelhappypack#53]
Might need to scale down some of the modifiers slightly and add a % manpower recovery. Among other things like naval morale.

**Comment by SpiritBaker** [comment]
Keep in mind that AI have reduced cap on wartime spendings for both Navy and Army, while having substantially more income. This is probably affects things you observing. 

Also you can just override in game difficulty with stuff u want. The game even have difficulty_hard.lua and difficulty_very_hard.lua, for overwriting defines specifically for higher difficulty.

**Comment by stackpoint** [comment]
The modpack is using the IV hard mode that scales in ages:
```
	land_morale = 0.075
	discipline = 0.035
	global_manpower = 5.0
	land_forcelimit_modifier = 0.1
	naval_forcelimit_modifier = 0.1
	naval_morale = 0.1
	heavy_ship_power = 0.075
	galley_power = 0.075
	light_ship_power = 0.075
	transport_power = 0.075
	global_sailors = 1000
	global_tax_modifier = 0.1
	production_efficiency = 0.1
	build_cost = -0.15
	monarch_admin_power = 1
	free_policy = 1
```

It also looks like the bonuses don't scale at all. All the triggered modifiers have the same values for the different ages.

Something else I noticed in naval battles is that your fleet can gain morale when it loses a ship because the average morale goes up. I believe flogi mentioned it was because he set NAVAL_CASUALTY_MIN_MORALE_DAMAGE to 0.

**Comment by mellester** [comment]
Cant we check in game what difficulty the game is set too?

**Comment by stackpoint** [comment]
This is something I came up with, since Mel mentioned to me that he didn't like the high combat modifiers that the AI got and the lack of recovery speed modifiers. We can set it so it actually scales into the ages too.

```
hard_mode_age1 = {
	potential = {
		current_age = age_of_discovery
		ai = yes
		has_global_flag = hard_mode
		NOT = {
			tag = REB
			tag = PIR
			tag = NAT
		}
	}
	trigger = {
		current_age = age_of_discovery
		ai = yes
		has_global_flag = hard_mode
	}
	
	#land
	land_morale = 0.04
	discipline = 0.02
	global_manpower = 5.0
	manpower_recovery_speed = 0.1
	land_forcelimit_modifier = 0.1
	
	
	#naval
	naval_morale = 0.04
	ship_durability = 0.02
	global_sailors = 500
	sailors_recovery_speed = 0.1
	naval_forcelimit_modifier = 0.1
	
	
	#gold
	global_tax_modifier = 0.1
	production_efficiency = 0.1
	state_maintenance_modifier = -0.1
	build_cost = -0.1
	
	#other
	free_policy = 1
}
```

**Comment by stackpoint** [comment]
Draft [Hard Mode.txt](https://github.com/TheDivexz/excelmakesbelhappypack/files/4603171/Hard.Mode.txt)
