### ISSUE TITLE
Start-up user experience

### ISSUE THREAD

**Issue by Grociu** [TheDivexz/excelmakesbelhappypack#66]
When you launch EU4, pick a country, and load in 1444, you are greeted by a set of popup events and new mod-specific decisions. This might be your first time launching and you don't yet know what everything does. A more structured and noob friendly explanation of features is needed.

* [x] A pop-up explaining to the player what the main features of the pack are might be nice.

* [x] Explain to the user that that clicking 'OK!' will lead to manual choice of settings.
* [x] Update the changelog (part of #59), I know there is some automation here. 
![image](https://user-images.githubusercontent.com/49829764/81482507-dbff0000-9237-11ea-9c77-d0f93c5c4121.png)

* [x] This needs a little better explanation
![image](https://user-images.githubusercontent.com/49829764/81482613-a60e4b80-9238-11ea-8de6-a1ed86a0114e.png)

* [x] Remove dots to fit the other decisions :) This has amazing hover tooltips btw.
![image](https://user-images.githubusercontent.com/49829764/81482649-e2da4280-9238-11ea-8ebe-a7401ec92f72.png)

* [x] These need an explanation that the setting cannot be changed after choice. Or implement a way to change the settings if that's possible. In general however these are well explained.
![image](https://user-images.githubusercontent.com/49829764/81482683-2df45580-9239-11ea-8005-1201a2fb079b.png)

DECISIONS:

As a part of startup actions you want to clear the decisions. They need a better explanation.
* [x] Hover tooltip on 'Manual Dev Growth'
* [x] Dev Ideas Dev Summary should be looked at here as well
* [x] Reform Monarchy - this is some kind of custom thing in this modpack right? What is this and why this exists?
* [x] State Edicts Are Currently Enabled - Explain this a little more, but it's OK as it is too
* [x] Empowered Requirements, very confusing needs explanation definately
* [x] Update Missions - You click this when switching tags sometimes, Hover tooltip should reflect that
* [x] You have the most income - Meek to Peak dummy from Arumba. Non functional, explain this.

![image](https://user-images.githubusercontent.com/49829764/81482706-5c723080-9239-11ea-99d0-7f8f18b7e26b.png)
* [x] Explain to the player this is meant for the AI and manual dev is still possible, better tooltips is always better :)
![image](https://user-images.githubusercontent.com/49829764/81482903-97289880-923a-11ea-9fa0-17ad5a8afa86.png)

**Comment by stackpoint** [comment]
>  Explain to the player this is meant for the AI and manual dev is still possible, better tooltips is always better :)

This is actually a debugging tool, we should disable it for human players.

>  You have the most income - Meek to Peak dummy from Arumba. Non functional, explain this.

This technically does work, it become available to click once the country has the most income.

>  This needs a little better explanation

It definitely does

>  Update the changelog (part of #59), I know there is some automation here.

This is directly lifted off the readme, so we should update that to update that event.

**Comment by Grociu** [comment]
> > You have the most income - Meek to Peak dummy from Arumba. Non functional, explain this.
> 
> This technically does work, it become available to click once the country has the most income.

Yeah, the intention behind this decision was to trigger a tag change on highest income for Meek to Peak. The trigger works indeed, but the button does nothing as it was WiP.

**Comment by stackpoint** [comment]
It more so that he didn't need to check the ledger so often and the decision would pop up in the alerts bar.

**Comment by Grociu** [comment]
Halfway done, test it on the [startup-ux ](https://github.com/TheDivexz/excelmakesbelhappypack/commits/startup-ux) branch.
