### ISSUE TITLE
Crash on reform overflow

### ISSUE THREAD

**Issue by plak20** [TheDivexz/excelmakesbelhappypack#79]
I was playing as Transoxiana>Timurids with the reforms Iqta+Strengthen noble privileges+Ulema guidance+Feudal levies and now trying to take administrative clergy to unlock the next empowered reforms (Divine blood/Monastic militarism), but when I take it my game crashes instantly
![20200514211809_1](https://user-images.githubusercontent.com/22401618/81998918-0f6fcf00-962a-11ea-935c-dbfef1405378.jpg)
![20200514211802_1](https://user-images.githubusercontent.com/22401618/81999012-4d6cf300-962a-11ea-9229-5abf16e559c9.jpg)

**Comment by stackpoint** [comment]
What version of the modpack are you using? Could we get a save file?

**Comment by plak20** [comment]
Sorry for the delay, the version is V0.2.2 and I was having trouble uploading to github (not used to it) so I just uploaded it to google drive https://drive.google.com/open?id=1PeaBCPa9QnuhHLYa-gibAbk1113tPJDI

**Comment by stackpoint** [comment]
For some reason the game is having trouble incrementing the variable and is causing the crash:
```
	effect = {
		change_variable = {
			which = Clergy_Influence
			value = 1
		}
	}
```

**Comment by plak20** [comment]
I have been messing with it for a while now and its seems to be related to the tier 2 reform, Strengthen noble privileges, when I change the tier 2 one I can select the tier 4 admin clergy , but if I then select the tier 2 noble privileges again it crashes the game
Edit: it seems that if you take the other reform that also gives noble influence, diplomatic positions, it also crashes, but if you take the other two it doesn't, so its probably related by the noble influence 

***(btw dont mind me closing the... issue?... new to github, I misunderstood  the "close issue thingy downn there")

**Comment by stackpoint** [comment]
Actually, I just remembered that the game crashes when there are too many reforms on a tier. So if your influence is too high in multiple factions, too many reforms appears which crash the game.

**Comment by stackpoint** [comment]
On the GE discord they mention that its likely that one of the ME custom reforms is causing GE to overflow past the max 8 reform slots.

**Comment by plak20** [comment]
ahhh, that makes sense, as I already have 8 slots at my tier 4 reforms as I am in the uzbek culture group and get the turkoman gunners

**Comment by stackpoint** [comment]
If you are familiar with text editing, you can fix this for your specific situation by 
commenting out/deleting the turkoman gunners ME reform: https://github.com/TheDivexz/excelmakesbelhappypack/blob/master/common/governments/00_governments.txt#L212

**Comment by Grociu** [comment]
How commonly can we expect this bug to occur (overflowing past 8 reform slots) and how can we remedy this as a more permanent solution?

**Comment by stackpoint** [comment]
I'm pretty sure the GE devs have set up their system so it never overflows. It's just that ME adds reforms which adds it's own problems.

**Comment by plak20** [comment]
Yep, I just did it and it works, thanks a lot for being so helpful, really apreciate you taking the time to find and help fix the issue

**Comment by plak20** [comment]
btw, should I close the issue?

**Comment by stackpoint** [comment]
We still need to figure out a general solution.

**Comment by plak20** [comment]
ah ok, well, either way I'm going to go now, good luck to you all, and might I add the mod has been great, good night!
