### ISSUE TITLE
Idea Variation Ideas Overflow

### ISSUE THREAD

**Issue by Pallan-Minerva** [TheDivexz/excelmakesbelhappypack#85]
Hello,

Have had this bug since first version of this pack. All Idea Variation custom idea groups repeat their ideas twice, but you cannot continue in the idea group after finishing the first set, so you are prevented from finishing idea groups.
![image](https://user-images.githubusercontent.com/65426352/82100915-0558d980-96d9-11ea-8a8b-47142e55add7.png)
![image](https://user-images.githubusercontent.com/65426352/82101061-654f8000-96d9-11ea-8895-0850b76661a2.png)

I disabled all other mods and this still existed, so I believe it's something in the pack. Any idea what it could be?

**Comment by stackpoint** [comment]
You need to delete the entire excelbel folder when reinstalling or updating.

**Comment by Grociu** [comment]
Pretty cool bug! It looks like the IV Idea Groups are doubled, would this happen if you put more than 7 ideas into a group? Or two copies of a file?

**Comment by Pallan-Minerva** [comment]
@stackpoint That fixed it. Thank you.

**Comment by stackpoint** [comment]
This started happening when someone renamed the idea groups files.
